import type { Level } from "./types";

export const LEVELS: Level[] = [
  {
    id: "tutorial",
    name: "SECTOR 01",
    width: 800,
    height: 600,
    start: { x: 80, y: 300 },
    par: 2,
    bodies: [
      {
        id: "p1",
        x: 400,
        y: 300,
        radius: 36,
        mass: 12000,
        kind: "planet",
        color: "#3a8f5c",
      },
      {
        id: "bh",
        x: 720,
        y: 300,
        radius: 28,
        mass: 18000,
        kind: "blackhole",
        color: "#6b4cff",
      },
    ],
  },
  {
    id: "slingshot",
    name: "SECTOR 02",
    width: 800,
    height: 600,
    start: { x: 60, y: 120 },
    par: 3,
    bodies: [
      {
        id: "p1",
        x: 220,
        y: 380,
        radius: 42,
        mass: 14000,
        kind: "planet",
        color: "#c45c3a",
      },
      {
        id: "p2",
        x: 480,
        y: 180,
        radius: 32,
        mass: 9000,
        kind: "planet",
        color: "#3a7fc4",
      },
      {
        id: "p3",
        x: 560,
        y: 460,
        radius: 38,
        mass: 11000,
        kind: "planet",
        color: "#8f8f3a",
      },
      {
        id: "bh",
        x: 740,
        y: 80,
        radius: 26,
        mass: 20000,
        kind: "blackhole",
        color: "#8b5cf6",
      },
    ],
  },
  {
    id: "gauntlet",
    name: "SECTOR 03",
    width: 800,
    height: 600,
    start: { x: 400, y: 540 },
    par: 4,
    bodies: [
      {
        id: "p1",
        x: 180,
        y: 320,
        radius: 34,
        mass: 10000,
        kind: "planet",
        color: "#3a8f8f",
      },
      {
        id: "p2",
        x: 400,
        y: 280,
        radius: 48,
        mass: 16000,
        kind: "planet",
        color: "#c43a6b",
      },
      {
        id: "p3",
        x: 620,
        y: 320,
        radius: 34,
        mass: 10000,
        kind: "planet",
        color: "#3a8f8f",
      },
      {
        id: "p4",
        x: 300,
        y: 120,
        radius: 28,
        mass: 7000,
        kind: "planet",
        color: "#8f6b3a",
      },
      {
        id: "p5",
        x: 500,
        y: 120,
        radius: 28,
        mass: 7000,
        kind: "planet",
        color: "#8f6b3a",
      },
      {
        id: "bh",
        x: 400,
        y: 48,
        radius: 30,
        mass: 22000,
        kind: "blackhole",
        color: "#a78bfa",
      },
    ],
  },
];
